spring:
  application:
      name: complaint-management-system

  datasource:
    url: ${db-url}
    username: ${db-uname}
    password: ${db-pass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    show-sql: true