INSERT INTO departments(department_id, department_name) VALUES
(1, 'Public Works Department (PWD)'),
(2, 'Electricity Department'),
(3, 'Water Supply Department'),
(4, 'Sanitation & Waste Management'),
(5, 'Municipal Corporation'),
(6, 'Parks & Recreation'),
(7, 'Traffic Police'),
(8, 'Building & Construction Authority'),
(9, 'Health Department'),
(10, 'Fire Department');




INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES
(1, 'Potholes on roads', 1),
(2, 'Broken sidewalks/footpaths', 1),
(3, 'Street cleaning issues', 1),
(4, 'Damaged road signs', 1),
(5, 'Unmarked speed breakers', 1),
(6, 'Blocked gutters/drains', 1),
(7, 'Street flooding after rain', 1),
(8, 'Missing or broken manhole covers', 1),
(9, 'Unpaved roads in residential areas', 1),
(10, 'Illegal dumping on public land', 1),
(11, 'Frequent power outages', 2),
(12, 'Broken or non-functioning street lights', 2),
(13, 'Electrical sparks or short circuits on poles', 2),
(14, 'Exposed electrical wires', 2),
(15, 'Transformer noise or overheating', 2),
(16, 'Delay in new electricity connection', 2),
(17, 'Voltage fluctuations', 2),
(18, 'Damaged electric meters', 2),
(19, 'Power theft or illegal connections', 2),
(20, 'Request for additional street lighting', 2),
(21, 'No water supply', 3),
(22, 'Water leakage from pipes', 3),
(23, 'Low water pressure', 3),
(24, 'Contaminated or dirty water', 3),
(25, 'Delay in new water connection', 3),
(26, 'Water meter issues', 3),
(27, 'Water tank cleaning required', 3),
(28, 'Broken fire hydrants', 3),
(29, 'Water supply timing complaints', 3),
(30, 'Unauthorized water connections', 3),
(31, 'Overflowing garbage bins', 4),
(32, 'Irregular garbage collection', 4),
(33, 'Dumping of construction debris', 4),
(34, 'Blocked stormwater drains', 4),
(35, 'Foul smell from garbage areas', 4),
(36, 'Uncollected bulky waste', 4),
(37, 'Lack of segregation of waste', 4),
(38, 'Stray animals rummaging garbage', 4),
(39, 'Garbage burning in public spaces', 4),
(40, 'Missing or damaged dustbins', 4),
(41, 'Illegal construction activities', 5),
(42, 'Encroachment on public property', 5),
(43, 'Unlicensed street vendors', 5),
(44, 'Poor street lighting in public areas', 5),
(45, 'Unapproved hoardings or posters', 5),
(46, 'Public toilets in disrepair', 5),
(47, 'Unauthorized demolition of structures', 5),
(48, 'Water logging on roads', 5),
(49, 'Complaints about property tax', 5),
(50, 'Noise from construction sites', 5),
(51, 'Broken park benches', 6),
(52, 'Damaged playground equipment', 6),
(53, 'Lack of cleanliness in parks', 6),
(54, 'Non-functional public toilets', 6),
(55, 'Overgrown grass or bushes', 6),
(56, 'Unauthorized parking in parks', 6),
(57, 'Vandalism of park property', 6),
(58, 'Lack of proper lighting in parks', 6),
(59, 'Issues with water fountains', 6),
(60, 'Noise or disturbance in park areas', 6),
(61, 'Traffic signal malfunction', 7),
(62, 'Illegal parking', 7),
(63, 'Encroachment on pedestrian crossings', 7),
(64, 'Lack of proper road markings', 7),
(65, 'Over-speeding in residential zones', 7),
(66, 'Reckless driving complaints', 7),
(67, 'Blocked bus stops', 7),
(68, 'Absence of pedestrian signals', 7),
(69, 'Non-functional speed cameras', 7),
(70, 'Unauthorized vehicle parking on footpaths', 7),
(71, 'Unauthorized construction', 8),
(72, 'Violation of building codes', 8),
(73, 'Unsafe scaffolding or construction sites', 8),
(74, 'Delay in building plan approvals', 8),
(75, 'Structural damage in buildings', 8),
(76, 'Encroachment on neighbors property', 8),
(77, 'Noise from construction work', 8),
(78, 'Non-compliance with safety norms', 8),
(79, 'Illegal alterations in buildings', 8),
(80, 'Complaints about demolition activities'),
(81, 'Mosquito breeding spots', 9),
(82, 'Stray dog nuisance', 9),
(83, 'Public area sanitation issues', 9),
(84, 'Food safety complaints in markets', 9),
(85, 'Rodent infestations', 9),
(86, 'Open garbage attracting insects', 9),
(87, 'Water stagnation causing disease risk', 9),
(88, 'Noise pollution complaints', 9),
(89, 'Lack of street hygiene', 9),
(90, 'Illegal disposal of medical waste', 9),
(91, 'Fire safety violations in buildings', 10),
(92, 'Blocked fire exits', 10),
(93, 'Faulty fire alarms or extinguishers', 10),
(94, 'Illegal storage of flammable materials', 10),
(95, 'Delay in fire safety inspections', 10),
(96, 'Fire hazards due to electrical faults', 10),
(97, 'Absence of fire hydrants nearby', 10),
(98, 'Fire safety drill complaints', 10),
(99, 'Non-compliance with fire safety laws', 10),
(100, 'Fire brigade response delays', 10);
