INSERT INTO departments(department_id, department_name) VALUES (1, 'Public Works Department (PWD)');
INSERT INTO departments(department_id, department_name) VALUES (2, 'Electricity Department');
INSERT INTO departments(department_id, department_name) VALUES (3, 'Water Supply Department');
INSERT INTO departments(department_id, department_name) VALUES (4, 'Sanitation & Waste Management');
INSERT INTO departments(department_id, department_name) VALUES (5, 'Municipal Corporation');
INSERT INTO departments(department_id, department_name) VALUES (6, 'Parks & Recreation');
INSERT INTO departments(department_id, department_name) VALUES (7, 'Traffic Police');
INSERT INTO departments(department_id, department_name) VALUES (8, 'Building & Construction Authority');
INSERT INTO departments(department_id, department_name) VALUES (9, 'Health Department');
INSERT INTO departments(department_id, department_name) VALUES (10, 'Fire Department');


INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (1, 'Potholes on roads', 1);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (2, 'Broken sidewalks/footpaths', 1);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (3, 'Street cleaning issues', 1);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (4, 'Damaged road signs', 1);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (5, 'Unmarked speed breakers', 1);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (6, 'Blocked gutters/drains', 1);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (7, 'Street flooding after rain', 1);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (8, 'Missing or broken manhole covers', 1);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (9, 'Unpaved roads in residential areas', 1);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (10, 'Illegal dumping on public land', 1);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (11, 'Frequent power outages', 2);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (12, 'Broken or non-functioning street lights', 2);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (13, 'Electrical sparks or short circuits on poles', 2);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (14, 'Exposed electrical wires', 2);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (15, 'Transformer noise or overheating', 2);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (16, 'Delay in new electricity connection', 2);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (17, 'Voltage fluctuations', 2);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (18, 'Damaged electric meters', 2);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (19, 'Power theft or illegal connections', 2);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (20, 'Request for additional street lighting', 2);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (21, 'No water supply', 3);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (22, 'Water leakage from pipes', 3);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (23, 'Low water pressure', 3);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (24, 'Contaminated or dirty water', 3);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (25, 'Delay in new water connection', 3);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (26, 'Water meter issues', 3);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (27, 'Water tank cleaning required', 3);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (28, 'Broken fire hydrants', 3);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (29, 'Water supply timing complaints', 3);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (30, 'Unauthorized water connections', 3);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (31, 'Overflowing garbage bins', 4);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (32, 'Irregular garbage collection', 4);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (33, 'Dumping of construction debris', 4);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (34, 'Blocked stormwater drains', 4);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (35, 'Foul smell from garbage areas', 4);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (36, 'Uncollected bulky waste', 4);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (37, 'Lack of segregation of waste', 4);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (38, 'Stray animals rummaging garbage', 4);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (39, 'Garbage burning in public spaces', 4);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (40, 'Missing or damaged dustbins', 4);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (41, 'Illegal construction activities', 5);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (42, 'Encroachment on public property', 5);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (43, 'Unlicensed street vendors', 5);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (44, 'Poor street lighting in public areas', 5);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (45, 'Unapproved hoardings or posters', 5);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (46, 'Public toilets in disrepair', 5);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (47, 'Unauthorized demolition of structures', 5);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (48, 'Water logging on roads', 5);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (49, 'Complaints about property tax', 5);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (50, 'Noise from construction sites', 5);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (51, 'Broken park benches', 6);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (52, 'Damaged playground equipment', 6);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (53, 'Lack of cleanliness in parks', 6);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (54, 'Non-functional public toilets', 6);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (55, 'Overgrown grass or bushes', 6);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (56, 'Unauthorized parking in parks', 6);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (57, 'Vandalism of park property', 6);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (58, 'Lack of proper lighting in parks', 6);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (59, 'Issues with water fountains', 6);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (60, 'Noise or disturbance in park areas', 6);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (61, 'Traffic signal malfunction', 7);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (62, 'Illegal parking', 7);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (63, 'Encroachment on pedestrian crossings', 7);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (64, 'Lack of proper road markings', 7);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (65, 'Over-speeding in residential zones', 7);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (66, 'Reckless driving complaints', 7);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (67, 'Blocked bus stops', 7);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (68, 'Absence of pedestrian signals', 7);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (69, 'Non-functional speed cameras', 7);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (70, 'Unauthorized vehicle parking on footpaths', 7);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (71, 'Unauthorized construction', 8);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (72, 'Violation of building codes', 8);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (73, 'Unsafe scaffolding or construction sites', 8);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (74, 'Delay in building plan approvals', 8);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (75, 'Structural damage in buildings', 8);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (76, 'Encroachment on neighbors property', 8);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (77, 'Noise from construction work', 8);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (78, 'Non-compliance with safety norms', 8);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (79, 'Illegal alterations in buildings', 8);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (80, 'Complaints about demolition activities', 8);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (81, 'Mosquito breeding spots', 9);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (82, 'Stray dog nuisance', 9);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (83, 'Public area sanitation issues', 9);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (84, 'Food safety complaints in markets', 9);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (85, 'Rodent infestations', 9);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (86, 'Open garbage attracting insects', 9);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (87, 'Water stagnation causing disease risk', 9);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (88, 'Noise pollution complaints', 9);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (89, 'Lack of street hygiene', 9);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (90, 'Illegal disposal of medical waste', 9);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (91, 'Fire safety violations in buildings', 10);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (92, 'Blocked fire exits', 10);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (93, 'Faulty fire alarms or extinguishers', 10);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (94, 'Illegal storage of flammable materials', 10);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (95, 'Delay in fire safety inspections', 10);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (96, 'Fire hazards due to electrical faults', 10);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (97, 'Absence of fire hydrants nearby', 10);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (98, 'Fire safety drill complaints', 10);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (99, 'Non-compliance with fire safety laws', 10);
INSERT INTO complaint_categories(category_id, category_name, department_id) VALUES (100, 'Fire brigade response delays', 10);